GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "First",
    "lastName": "Last",
    "role": "Project Manager"
}

###

PUT http://localhost:3000/users/66eed7f3d1381d2673f541ef
Content-Type: application/json

{
    "firstName": "X",
    "lastName": "X",
    "role": "Project Manager",
    "name": "project2"
}

###
DELETE http://localhost:3000/users/66eed7f3d1381d2673f541ef

###


